name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: issues-updater-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export NODE_PATH=$NODE_PATH:`npm root -g`
          npm i -g @octokit/core
          node ./.github/scripts/paperReview.js
