name: readme_update

on:
  issues:
    types: [labeled, unlabeled]

  project_card:
    types: [converted, moved, deleted]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export NODE_PATH=$NODE_PATH:`npm root -g`
          npm i -g @octokit/core
          node .github/scripts/readme.js

          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto commit"
          git push
